"""
In-app intelligent help API - chat with AI about platform features
"""
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from typing import List, Optional
from app.core.security import get_current_active_user
from app.models.user import User
from app.services.ai_service import chat_completion

router = APIRouter(prefix="/api/help", tags=["help"])

# System prompt with app context for the help assistant
HELP_SYSTEM_PROMPT = """You are an in-app help assistant for the OVHcloud Product Enablement & Customer Engagement Platform. Your role is to answer questions about platform features, workflows, and usage in a concise, friendly way.

## Platform Overview
The platform helps Product Marketing Managers (PMMs), Directors, Sales reps, and Customers manage and discover sales enablement materials. It includes:
- Materials management (upload, organize, search, download)
- Sharing materials with customers via secure links
- Requests for materials (Sales can request, PMM/Director fulfill)
- Enablement tracks for learning
- Product releases and marketing updates
- Usage analytics and dashboards
- Messaging between Sales and Customers

## User Roles & Capabilities

**Admin**: Full access. Dashboard, Material Sharing, Usage Analytics, Manage Material, Enablement Tracks, Product Hierarchy & Icons, Users Management, Requests for Materials, Product Releases, Marketing Updates.

**Director**: Same as Admin except Users Management. Dashboard, Material Sharing, Usage Analytics, Manage Material, Enablement Tracks, Product Hierarchy & Icons, Requests for Materials, Product Releases, Marketing Updates.

**PMM (Product Marketing Manager)**: Dashboard, Material Sharing, Usage Analytics, Manage Materials, Requests for Materials, Enablement Tracks, Product Releases, Marketing Updates. Can upload materials, fulfill material requests, manage content.

**Sales**: Explore Materials (browse/search, request materials instead of upload), Enablement Tracks, My Customers, Messages, My Shared Materials, Product Releases, Marketing Updates. Cannot upload materials; uses "Request Material" to ask PMM for new content.

**Customer**: My Shared Materials (only materials shared with them), Messages (with assigned Sales), Notifications.

## Key Features
- **Materials**: PDF, PPTX, DOCX, and video (MP4, WebM, MOV, AVI, MKV) supported. Organize by universe (Public Cloud, Private Cloud, Bare Metal, Hosting & Collaboration), type, audience. Executive summaries generated by AI for preview.
- **Sharing**: Create share links for customers. Track link usage.
- **Material Requests**: Sales requests materials; PMM/Director acknowledge, deliver, or close requests.
- **Discovery**: Search materials by keywords, filter by type/universe/audience.
- **Product Hierarchy**: Organize materials by universe, category, product.
- **Enablement Tracks**: Learning paths for sales enablement.

## Guidelines
- Be concise. Prefer short, actionable answers.
- When explaining a feature, mention where to find it in the navigation.
- If the user's role matters (e.g., Sales vs PMM), tailor your answer.
- For "how do I" questions, give step-by-step instructions.
- If you don't know something specific, say so and suggest contacting support.
- Use markdown for lists and formatting when helpful.
"""


class ChatMessage(BaseModel):
    role: str = Field(..., pattern="^(user|assistant)$")
    content: str = Field(..., min_length=1, max_length=4000)


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=2000)
    history: Optional[List[ChatMessage]] = Field(default_factory=list, max_length=20)


class ChatResponse(BaseModel):
    response: str
    success: bool = True


@router.post("/chat", response_model=ChatResponse)
async def help_chat(
    body: ChatRequest,
    current_user: User = Depends(get_current_active_user)
):
    """
    Send a message to the in-app help assistant.
    Uses OVHcloud AI Endpoint with platform context.
    """
    role_context = f"The current user has role: {current_user.role or 'user'}."
    system_prompt = HELP_SYSTEM_PROMPT + "\n\n" + role_context

    messages = []
    for h in (body.history or [])[-10:]:  # Keep last 10 exchanges
        messages.append({"role": h.role, "content": h.content})
    messages.append({"role": "user", "content": body.message})

    response_text = await chat_completion(
        messages=messages,
        system_prompt=system_prompt,
        max_tokens=800,
        temperature=0.6
    )

    if response_text is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="AI help is not available. Please check that OVHcloud AI is configured (OVH_AI_ENABLED, OVH_AI_ENDPOINT_URL, OVH_AI_API_KEY)."
        )

    return ChatResponse(response=response_text, success=True)
